// Mongoose schema for leads (Lead)
import mongoose from "mongoose";

const RentLeadSchema = new mongoose.Schema(
  {
    ownerName: String,
    ownerPhone: String,
    parking: {
      type: String,
      enum: ["No Parking", "1 Car", "2 Car", "3+ Car", "Bike Only", "Visitor"],
      default: "No Parking",
    },
    security: String,
    flat: {
      type: String,
      enum: [
        "1RK",
        "1BHK",
        "2BHK",
        "3BHK",
        "4BHK",
        "5BHK",
        "Independent House",
        "Studio Apartment",
        "PG/Hostel",
        "Not Provided",
      ],
      default: "Not Provided",
    }, // Flat type
    rent: String,
    advance: String,
    source: {
      type: String,
      enum: [
        "PORTAL",
        "CRM",
        "FACEBOOK",
        "INSTAGRAM",
        "WHATSAPP",
        "REFERRAL",
        "OTHER",
      ],
      default: "CRM",
    }, // Default source
    mailStatus: {
      type: String,
      enum: ["success", "failed"],
      default: "failed",
    }, // Status of the contact mail
    availability: {
      type: String,
      enum: ["immediate", "1 month", "2 months", "3+ months", "Not Provided"],
      default: "Not Provided",
    }, // Status of the contact mail
    notes: { type: String },
    // project: { type: String },
    location: {
      type: String,
      enum: [
        "Koramangala 1st Block",
        "Koramangala 2nd Block",
        "Koramangala 3rd Block",
        "Koramangala 4th Block",
        "Koramangala 5th Block",
        "Koramangala 6th Block",
        "Koramangala 8th Block",
        "Koramangala",
        "Indiranagar",
        "Indira Nagar Extension",
        "HSR Layout",
        "HSR 1st Sector",
        "HSR 2nd Sector",
        "HSR 3rd Sector",
        "HSR 4th Sector",
        "HSR 5th Sector",
        "HSR 6th Sector",
        "HSR 7th Sector",
        "HSR 8th Sector",
        "HSR 9th Sector",
        "HSR 10th Sector",
        "BTM Layout",
        "Ejipura",
        "Jayanagar",
        "Adugodi",
        "Madiwala",
        "Domlur",
        "Vivek Nagar",
        "Jakkasandra",
        "Venkatapura",
        "National Games Village Complex",
        "Whitefield",
        "Marathahalli",
        "Sarjapur Road",
        "Electronic City",
        "Bannerghatta Road",
        "Malleshwaram",
        "Rajajinagar",
        "Basavanagudi",
        "J P Nagar",
        "Banashankari",
        "Yelahanka",
        "Hebbal",
        "Hebbal Kempapura",
        "Sadashivanagar",
        "MG Road",
        "Richmond Town",
        "Ulsoor",
        "Frazer Town",
        "Vasanth Nagar",
        "Shivajinagar",
        "Cox Town",
        "Hoysala Nagar",
        "Kalyan Nagar",
        "Kammanahalli",
        "HBR Layout",
        "RMV Extension",
        "Sahakara Nagar",
        "CV Raman Nagar",
        "Byatarayanapura",
        "Peenya",
        "Kengeri",
        "Kanakapura Road",
        "Hosur Road",
        "Banaswadi",
        "Kaggadasapura",
        "Mahadevapura",
        "Varthur",
        "KR Puram",
        "K R Puram",
        "Bellandur",
        "Kundalahalli",
        "Not Provided",
      ],
      default: "Not Provided",
    },
  },
  { timestamps: true }
);

const RentLead = mongoose.model("RentLead", RentLeadSchema);
export default RentLead;
